name: Dev Doc Deploy

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'site-documentation/docs/**/*.md'
  workflow_dispatch:

jobs:
  npm_compile:
    defaults:
      run:
        working-directory: site-documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: site-documentation/package-lock.json
      - run: npm install
      - run: npm run build
      - name: Display structure of downloaded files
        run: ls -R
      - uses: actions/upload-artifact@v2
        with:
          name: compiledDocumentation
          path: build/
          if-no-files-found: error
  hosting_deploy:
    needs: npm_compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: compiledDocumentation
          path: public/docs/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLF_EVENT_PLATFORM }}"
          expires: 30d
          projectId: golf-event-platform
          channelId: dev
          target: docs
