name: Dev Doc Deploy

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'site-documentation/docs/**/*.md'
  workflow_dispatch:

jobs:
  npm_compile:
    defaults:
      run:
        working-directory: site-documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run build
  file_transfer:
    needs: npm_compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy files
        uses: canastro/copy-file-action@master
        with:
          source: "site-documentation/**"
          target: "public/docs/**"
  hosting_deploy:
    needs: [npm_compile, file_transfer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLF_EVENT_PLATFORM }}"
          expires: 30d
          projectId: golf-event-platform
          channelId: dev
          target: docs
