name: Prod Fxn Deploy

on:
  push:
    branches: [dev]
    paths:
      - '/functions/index.js'

jobs:
  function_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Deploy Functions
        uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
