name: Full Production Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  hosting_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLF_EVENT_PLATFORM }}"
          projectId: golf-event-platform
          channelId: live
  function_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Deploy Functions
        uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  
